<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE bookstore [
    <!ELEMENT bookstore (book+)>
    <!ELEMENT book (title, author, year, price, description?)>
    <!ELEMENT title (#PCDATA)>
    <!ELEMENT author (#PCDATA)>
    <!ELEMENT year (#PCDATA)>
    <!ELEMENT price (#PCDATA)>
    <!ELEMENT description (#PCDATA)>
    <!ATTLIST book category CDATA #REQUIRED>
    <!ATTLIST title lang CDATA #IMPLIED>
]>
<bookstore>
    <book category="cooking">
        <title lang="en">Everyday Italian</title>
        <author>Giada De Laurentiis</author>
        <year>2005</year>
        <price currency="USD">30.00</price>
        <description><![CDATA[Книга о <итальянской> кухне & рецептах]]></description>
    </book>

    <book category="children">
        <title lang="en" edition="first">Harry Potter</title>
        <author>J.K. Rowling</author>
        <year>2005</year>
        <price>29.99</price>
    </book>

    <book category="web" cover="paperback">
        <title lang="en">Learning XML</title>
        <author>Erik T. Ray</author>
        <year>2003</year>
        <price>39.95</price>
        <description>Практическое руководство по XML</description>
    </book>

    <empty-element attr="value"/>

    <mixed>Текст с <bold>жирным</bold> и <italic>курсивным</italic> форматированием</mixed>

    <entities>&amp; &lt; &gt; &apos; &quot; &#65; &#x41;</entities>
</bookstore>